import { MaterialProvider } from "@/mui/MaterialProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "task management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MaterialProvider>{children}</MaterialProvider>
      </body>
    </html>
  );
}
